version: "3.9"
services:
  database:
    image: postgres:12.12
    restart: always
    container_name: chat-database
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD:-password}
      - POSTGRES_DB=${DB_DATABASE:-chat}
    volumes:
      - dbdata:/var/lib/postgresql/data
    expose:
      - "5432"

  http-server:
    build:
      context: ./http-server
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    image: chat_http_server
    container_name: chat-http-server
    restart: always
    ports:
      - "${HTTP_SERVER_PORT:-5000}:5000"
    volumes:
      - ./http-server:/app
      - http_server_vendor:/app/vendor

  ws-server:
    build: 
      context: ./ws-server
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    image: chat_ws_server
    container_name: chat-ws-server
    restart: always
    ports:
      - "${WS_SERVER_PORT:-3000}:3000"
    volumes:
      - ./ws-server:/app
      - ws_server_node_modules:/app/node_modules

  client:
    build:
      context: ./client
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    image: chat_client
    container_name: chat-client
    restart: always
    ports:
      - "${CLIENT_PORT:-4200}:4200"
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules

volumes:
  dbdata:
  http_server_vendor:
  ws_server_node_modules:
  client_node_modules:
