version: "3.9"
services:
  server:
    build:
      context: ./server
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    image: chat_server
    container_name: chat-server
    restart: always
    ports:
      - "${SERVER_PORT:-5000}:5000"
    volumes:
      - ./server:/app
      - server_vendor:/app/vendor

  client:
    build:
      context: ./client
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    image: chat_client
    container_name: chat-client
    restart: always
    ports:
      - "${CLIENT_PORT:-4200}:4200"
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules

volumes:
  server_vendor:
  client_node_modules:
